### ISSUE TITLE
Screenshot not applied to widget

### ISSUE THREAD

**Issue by betraydan** [chaubss/Hidden-Widgets#3]
After selecting screenshot in the app and returning to add the widget to the homescreen the widget remains empty with “open app to set up widget” in widget area. 

iOS14 public release
iPhoneX

**Comment by chaubss** [comment]
@betraydan I am unable to reproduce your issue with the latest iOS 14 public release and Xcode 12. 
Please make sure your app group names have been set correctly for each target. Refer to the [README](https://github.com/chaubss/Hidden-Widgets/blob/master/README.md) file for detailed installation instructions on how to set up the app group correctly.

**Comment by betraydan** [comment]
Resolved it. It was indeed a typo on one of the app groups i overlooked. Thanks again for this app. 🙌
