### ISSUE TITLE
The provisioning profile has expired

### ISSUE THREAD

**Issue by GabrielSalach** [chaubss/Hidden-Widgets#6]
I can't install the app at all. I tried on iTunes (Windows 10) but I get the "unable to download" error message on my iPhone, and when using an alternative methode like Diawi, it says that the provisioning profile has expired on the 26/09. 
Also, it seems that my UDID is not contained in the profile.

I'm on the public release of iOS 14.0.1

**Comment by askari01** [comment]
@GabrielSalach this is not an issue. you need paid apple dev account.

**Comment by chaubss** [comment]
@GabrielSalach This isn't an issue, however, you do not need a paid developer account. You can install from Xcode using a free account as well. If you want to install from the IPA, you have to sign the app. I've tested AltStore and it works best as it also keeps the app extensions. Please try that.
